// web/src/components/Project.vue
<template>
  <header>
    <router-link to="/" class="btn btn-secondary">Back</router-link>
    <span class="page-title">{{project.name}}</span>
    <button type="button" @click="save()" class="btn btn-primary">Save</button>
  </header>

  <div class="project-wrapper">
    <div class="project-content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-sm-12 col-md-6">
            <label for="name">Name</label>
            <input id="name" v-model="project.name" type="text" class="form-control" placeholder="Name">
          </div>
          <div class="col-sm-12 col-md-6">
            <label for="totalCost">Total Cost</label>
            <div class="input-group">
              <span class="input-group-text">$</span>
              <input id="totalCost" v-model="project.totalCost" type="text" class="form-control" placeholder="Total Cost">
            </div>
          </div>
          <div class="col-sm-12 col-md-6">
            <label for="description">Description</label>
            <textarea id="description" v-model="project.description" class="form-control"></textarea>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Project',
  data () {
    return {
      project: {}
    }
  },
  mounted () {
    this.project = this.$store.getters.getProjectById(this.$route.params.id)
  }
}
</script>

<style scoped>
</style>

// old/simply-projects/src/app/project/project.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { MOCK_PROJECTS } from '../mocks/mock-projects';
import { Project } from '../models/project';

@Component({
  selector: 'app-project',
  templateUrl: './project.component.html',
  styleUrls: ['./project.component.css']
})
export class ProjectComponent implements OnInit {
  project: Project;

  constructor(private route: ActivatedRoute,
              private router: Router) { }

  ngOnInit() {
    this.getProject();
  }

  private getProject() {
    const id = +this.route.snapshot.paramMap.get('id');
    this.project = MOCK_PROJECTS.find(x => x.id === id);
  }

  back() {
    this.router.navigate(['/']);
  }

  save() {
    this.router.navigate(['/']);
  }

}

<header>
  <button pButton type="button" (click)="back()" label="Back" class="ui-button-raised ui-button-secondary"></button>
  <span class="page-title">{{project.name}}</span>
  <button pButton type="button" (click)="save()" label="Save" class="ui-button-raised"></button>
</header>

<div class="project-wrapper">
  <div class="project-content">
    <div class="ui-fluid">
      <div class="ui-g">
        <div class="ui-g-12 ui-md-6">
          <label for="name">Name</label>
          <input id="name" type="text" pInputText placeholder="Name" [(ngModel)]="project.name">
        </div>
        <div class="ui-g-12 ui-md-6"> 
          <label for="totalCost">Total Cost</label>
          <div class="ui-inputgroup">
            <span class="ui-inputgroup-addon">$</span> 
            <input id="totalCost" type="text" pInputText pKeyFilter="money" placeholder="Total Cost" [(ngModel)]="project.totalCost">
          </div>
        </div>
        <div class="ui-g-12 ui-md-6">
          <label for="description">Description</label>
          <textarea id="description" pInputTextarea autoResize="autoResize" [(ngModel)]="project.description"></textarea>
        </div>
      </div>
    </div>
  </div>
</div>
