// old/simply-projects/src/app/project/project.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { MOCK_PROJECTS } from '../mocks/mock-projects';
import { Project } from '../models/project';

@Component({
  selector: 'app-project',
  templateUrl: './project.component.html',
  styleUrls: ['./project.component.css']
})
export class ProjectComponent implements OnInit {
  project: Project;

  constructor(private route: ActivatedRoute,
              private router: Router) { }

  ngOnInit() {
    this.getProject();
  }

  private getProject() {
    const id = +this.route.snapshot.paramMap.get('id');
    this.project = MOCK_PROJECTS.find(x => x.id === id);
  }

  back() {
    this.router.navigate(['/']);
  }

  save() {
    this.router.navigate(['/']);
  }

}

<header>
  <button pButton type="button" (click)="back()" label="Back" class="ui-button-raised ui-button-secondary"></button>
  <span class="page-title">{{project.name}}</span>
  <button pButton type="button" (click)="save()" label="Save" class="ui-button-raised"></button>
</header>

<div class="project-wrapper">
  <div class="project-content">
    <div class="ui-fluid">
      <div class="ui-g">
        <div class="ui-g-12 ui-md-6">
          <label for="name">Name</label>
          <input id="name" type="text" pInputText placeholder="Name" [(ngModel)]="project.name">
        </div>
        <div class="ui-g-12 ui-md-6"> 
          <label for="totalCost">Total Cost</label>
          <div class="ui-inputgroup">
            <span class="ui-inputgroup-addon">$</span> 
            <input id="totalCost" type="text" pInputText pKeyFilter="money" placeholder="Total Cost" [(ngModel)]="project.totalCost">
          </div>
        </div>
        <div class="ui-g-12 ui-md-6">
          <label for="description">Description</label>
          <textarea id="description" pInputTextarea autoResize="autoResize" [(ngModel)]="project.description"></textarea>
        </div>
      </div>
    </div>
  </div>
</div>

// web/src/components/Project/Project.vue
<template>
  <div class="page-header" v-if="project">
    <router-link to="/"
      class="btn btn-secondary">Back</router-link>
    <span class="page-title">{{project.name}}</span>
    <button type="button"
      @click="save()"
      class="btn btn-primary">Save</button>
  </div>

  <div class="project-wrapper" v-if="project">
    <div class="project-content flex-column">
      <label for="name">Name</label>
      <input id="name"
        class="form-control input-column"
        v-model="project.name"
        type="text"
        placeholder="Name">

      <label for="totalCost">Total Cost</label>
      <div class="input-group input-column">
        <span class="input-group-text">$</span>
        <input id="totalCost"
          v-model="project.totalCost"
          type="text"
          class="form-control"
          placeholder="Total Cost">
      </div>

      <label for="description">Description</label>
      <textarea id="description"
        class="form-control input-column"
        v-model="project.description"></textarea>

      <Materials :projectId="project?.id" />
    </div>
  </div>
</template>

<script>
import { mapGetters } from 'vuex'
import Materials from './Materials.vue'

export default {
  name: 'Project',
  components: {
    Materials
  },
  data () {
    return {
      project: null
    }
  },
  computed: {
    ...mapGetters('projects', {
      findProject: 'find'
    })
  },
  mounted () {
    this.project = this.findProject(+this.$route.params.id)
  }
}
</script>

<style scoped lang="scss">

  .project-content {
    .input-column {
      width: 300px;
      max-width: 100%;
      margin-bottom: 10px;
    }

    textarea {
      resize: none;
    }
  }
</style>
